### PR TITLE
Change default value for HTTPLogger

### PR DESCRIPTION
**Pull request by ashtongraves**

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM but we may as well just rip this out entirely

**Comment by ashtongraves** [comment]
> LGTM but we may as well just rip this out entirely

So I think that we have that set in pretty much all of our ce helm files, would ripping that out cause it to error out? I guess I'm just wondering about the coordination of ce changes if we do make a change to our helm chart that causes changes to be made on all existing CE helms?

**Comment by brianhlin** [comment]
> So I think that we have that set in pretty much all of our ce helm files, would ripping that out cause it to error out?

I don't think so. Ripping out the relevant bits in the template files should cause any references in values files to be a no-op.

**Comment by matyasselmeci** [comment]
Just make sure the templates themselves deal with having a missing key.

**Comment by brianhlin** [comment]
If the templates don't reference the key, I don't think we need to worry about handling a missing key!

**Pull request closed without merging**
