### PR TITLE
Adds ProxyJumpUser

### PR DESCRIPTION
**Pull request by ashtongraves**

### CODE REVIEW

**Comment by ashtongraves** [comment]
@brianhlin @JaimeFrey 

Helm companion to https://github.com/opensciencegrid/docker-compute-entrypoint/pull/110

**Review by JaimeFrey — APPROVED** [review]
Looks good to me.

**Comment by brianhlin** [comment]
@ashtongraves you'll need to bump the helm version but otherwise LGTM

**Comment by ashtongraves** [comment]
Done. Can this be merged?

**Pull request merged**
